// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(SafirDbContext))]
    [Migration("20250217235935_AddAddress_SeedData")]
    partial class AddAddress_SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Address.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("RegisteredBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDelete = false,
                            Name = "تبریز",
                            ProvinceId = 1,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            IsDelete = false,
                            Name = "ارومیه",
                            ProvinceId = 2,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            IsDelete = false,
                            Name = "اردبیل",
                            ProvinceId = 3,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            IsDelete = false,
                            Name = "اصفهان",
                            ProvinceId = 4,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            IsDelete = false,
                            Name = "کرج",
                            ProvinceId = 5,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            IsDelete = false,
                            Name = "ایلام",
                            ProvinceId = 6,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            IsDelete = false,
                            Name = "بوشهر",
                            ProvinceId = 7,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            IsDelete = false,
                            Name = "تهران",
                            ProvinceId = 8,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            IsDelete = false,
                            Name = "شهرکرد",
                            ProvinceId = 9,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            IsDelete = false,
                            Name = "بیرجند",
                            ProvinceId = 10,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            IsDelete = false,
                            Name = "مشهد",
                            ProvinceId = 11,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            IsDelete = false,
                            Name = "بجنورد",
                            ProvinceId = 12,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            IsDelete = false,
                            Name = "اهواز",
                            ProvinceId = 13,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            IsDelete = false,
                            Name = "زنجان",
                            ProvinceId = 14,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            IsDelete = false,
                            Name = "سمنان",
                            ProvinceId = 15,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            IsDelete = false,
                            Name = "زاهدان",
                            ProvinceId = 16,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            IsDelete = false,
                            Name = "شیراز",
                            ProvinceId = 17,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            IsDelete = false,
                            Name = "قزوین",
                            ProvinceId = 18,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            IsDelete = false,
                            Name = "قم",
                            ProvinceId = 19,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            IsDelete = false,
                            Name = "سنندج",
                            ProvinceId = 20,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            IsDelete = false,
                            Name = "کرمان",
                            ProvinceId = 21,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            IsDelete = false,
                            Name = "کرمانشاه",
                            ProvinceId = 22,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            IsDelete = false,
                            Name = "یاسوج",
                            ProvinceId = 23,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            IsDelete = false,
                            Name = "گرگان",
                            ProvinceId = 24,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            IsDelete = false,
                            Name = "رشت",
                            ProvinceId = 25,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            IsDelete = false,
                            Name = "خرم‌آباد",
                            ProvinceId = 26,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            IsDelete = false,
                            Name = "ساری",
                            ProvinceId = 27,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            IsDelete = false,
                            Name = "اراک",
                            ProvinceId = 28,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            IsDelete = false,
                            Name = "بندرعباس",
                            ProvinceId = 29,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            IsDelete = false,
                            Name = "همدان",
                            ProvinceId = 30,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            IsDelete = false,
                            Name = "یزد",
                            ProvinceId = 31,
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Address.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegisteredBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDelete = false,
                            Name = "آذربایجان شرقی",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            IsDelete = false,
                            Name = "آذربایجان غربی",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            IsDelete = false,
                            Name = "اردبیل",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            IsDelete = false,
                            Name = "اصفهان",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            IsDelete = false,
                            Name = "البرز",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            IsDelete = false,
                            Name = "ایلام",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            IsDelete = false,
                            Name = "بوشهر",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            IsDelete = false,
                            Name = "تهران",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            IsDelete = false,
                            Name = "چهارمحال و بختیاری",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            IsDelete = false,
                            Name = "خراسان جنوبی",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            IsDelete = false,
                            Name = "خراسان رضوی",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            IsDelete = false,
                            Name = "خراسان شمالی",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            IsDelete = false,
                            Name = "خوزستان",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            IsDelete = false,
                            Name = "زنجان",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            IsDelete = false,
                            Name = "سمنان",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            IsDelete = false,
                            Name = "سیستان و بلوچستان",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            IsDelete = false,
                            Name = "فارس",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            IsDelete = false,
                            Name = "قزوین",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            IsDelete = false,
                            Name = "قم",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            IsDelete = false,
                            Name = "کردستان",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            IsDelete = false,
                            Name = "کرمان",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            IsDelete = false,
                            Name = "کرمانشاه",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            IsDelete = false,
                            Name = "کهگیلویه و بویراحمد",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            IsDelete = false,
                            Name = "گلستان",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            IsDelete = false,
                            Name = "گیلان",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            IsDelete = false,
                            Name = "لرستان",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            IsDelete = false,
                            Name = "مازندران",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            IsDelete = false,
                            Name = "مرکزی",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            IsDelete = false,
                            Name = "هرمزگان",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            IsDelete = false,
                            Name = "همدان",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            IsDelete = false,
                            Name = "یزد",
                            RegisteredBy = "Masou With Seed Data",
                            RegisteredDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Address.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("RegisteredBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProvinceId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Domain.Entities.HumanResources.EmployeeManagement.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("RegisteredBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Domain.Entities.HumanResources.EmployeeManagement.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthCertificateNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DateOfEmployment")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfExit")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("Education")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FamiliarPhone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IRCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ImageAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int");

                    b.Property<string>("RegisteredBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeID")
                        .IsUnique();

                    b.HasIndex("PositionId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Domain.Entities.HumanResources.EmployeeManagement.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RegisteredBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("Domain.Entities.MSCRM.Clue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClueCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("ClueName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConverted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MarketerId")
                        .HasColumnType("int");

                    b.Property<string>("RegisteredBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MarketerId");

                    b.ToTable("Clues");
                });

            modelBuilder.Entity("Domain.Entities.MSCRM.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("CustomerGender")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MarketerId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("RegisteredBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MarketerId");

                    b.HasIndex("RegionId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Domain.Entities.MSCRM.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasicDriversLicense")
                        .HasColumnType("int");

                    b.Property<string>("DateOfIssue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("RegisteredBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ValidityPeriod")
                        .HasColumnType("int");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RegionId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("Domain.Entities.MSCRM.Marketer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("RegisteredBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RegionId");

                    b.ToTable("Marketers");
                });

            modelBuilder.Entity("Domain.Entities.ProductsCategories.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("RegisteredBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Domain.Entities.ProductsCategories.CategoryProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("RegisteredBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("CategoryProducts");
                });

            modelBuilder.Entity("Domain.Entities.ProductsCategories.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("RegisteredBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Domain.Entities.Site.SiteMenu.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("RegisteredBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("Domain.Entities.Site.SiteMenu.MenuAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("RegisteredBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("MenuAccesses");
                });

            modelBuilder.Entity("Domain.Entities.oredersANDinvoices.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MarketerId")
                        .HasColumnType("int");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("RegisteredBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DriverId");

                    b.HasIndex("MarketerId");

                    b.HasIndex("RegionId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Domain.Entities.Address.City", b =>
                {
                    b.HasOne("Domain.Entities.Address.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Domain.Entities.Address.Region", b =>
                {
                    b.HasOne("Domain.Entities.Address.City", "City")
                        .WithMany("Regions")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Address.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Domain.Entities.HumanResources.EmployeeManagement.Employee", b =>
                {
                    b.HasOne("Domain.Entities.HumanResources.EmployeeManagement.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.HumanResources.EmployeeManagement.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Domain.Entities.HumanResources.EmployeeManagement.Position", b =>
                {
                    b.HasOne("Domain.Entities.HumanResources.EmployeeManagement.Department", "Department")
                        .WithMany("Positions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Domain.Entities.MSCRM.Clue", b =>
                {
                    b.HasOne("Domain.Entities.MSCRM.Marketer", "Marketer")
                        .WithMany("Clues")
                        .HasForeignKey("MarketerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marketer");
                });

            modelBuilder.Entity("Domain.Entities.MSCRM.Customer", b =>
                {
                    b.HasOne("Domain.Entities.MSCRM.Marketer", "Marketer")
                        .WithMany("Customers")
                        .HasForeignKey("MarketerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Address.Region", "Region")
                        .WithMany("Customers")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marketer");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Domain.Entities.MSCRM.Driver", b =>
                {
                    b.HasOne("Domain.Entities.HumanResources.EmployeeManagement.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Address.Region", "Region")
                        .WithMany("Drivers")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Domain.Entities.MSCRM.Marketer", b =>
                {
                    b.HasOne("Domain.Entities.HumanResources.EmployeeManagement.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Address.Region", "Region")
                        .WithMany("Marketers")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Domain.Entities.ProductsCategories.Category", b =>
                {
                    b.HasOne("Domain.Entities.ProductsCategories.Category", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Domain.Entities.ProductsCategories.CategoryProduct", b =>
                {
                    b.HasOne("Domain.Entities.ProductsCategories.Category", "Category")
                        .WithMany("CategoryProducts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ProductsCategories.Product", "Product")
                        .WithMany("CategoryProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.ProductsCategories.Product", b =>
                {
                    b.HasOne("Domain.Entities.ProductsCategories.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.Site.SiteMenu.Menu", b =>
                {
                    b.HasOne("Domain.Entities.Site.SiteMenu.Menu", "Parent")
                        .WithMany("SubMenus")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Entities.Site.SiteMenu.MenuAccess", b =>
                {
                    b.HasOne("Domain.Entities.Site.SiteMenu.Menu", "Menu")
                        .WithMany("AccessMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Domain.Entities.oredersANDinvoices.Order", b =>
                {
                    b.HasOne("Domain.Entities.MSCRM.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.MSCRM.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.MSCRM.Marketer", "Marketer")
                        .WithMany()
                        .HasForeignKey("MarketerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Address.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Driver");

                    b.Navigation("Marketer");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Domain.Entities.Address.City", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("Domain.Entities.Address.Province", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Domain.Entities.Address.Region", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Drivers");

                    b.Navigation("Marketers");
                });

            modelBuilder.Entity("Domain.Entities.HumanResources.EmployeeManagement.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("Domain.Entities.HumanResources.EmployeeManagement.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Domain.Entities.MSCRM.Marketer", b =>
                {
                    b.Navigation("Clues");

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Domain.Entities.ProductsCategories.Category", b =>
                {
                    b.Navigation("CategoryProducts");
                });

            modelBuilder.Entity("Domain.Entities.ProductsCategories.Product", b =>
                {
                    b.Navigation("CategoryProducts");
                });

            modelBuilder.Entity("Domain.Entities.Site.SiteMenu.Menu", b =>
                {
                    b.Navigation("AccessMenus");

                    b.Navigation("SubMenus");
                });
#pragma warning restore 612, 618
        }
    }
}
